### ISSUE TITLE
0 genes parsed

### ISSUE THREAD

**Issue by jjenny** [getzlab/rnaseqc#35]
Can you specify what features should be listed on the gtf file? I am trying to run rnaseqc on a genome that we annotated ourselves and I keep getting '0 genes parsed' with my input gtf file.

**Comment by francois-a** [comment]
The GTF file should follow the GENCODE specification at https://www.gencodegenes.org/pages/data_format.html

A collapsed annotation that has a single transcript per gene should be used. A script for generating this is available at https://github.com/broadinstitute/gtex-pipeline/tree/v9/gene_model.
