### ISSUE TITLE
problem with installation

### ISSUE THREAD

**Issue by kac2053** [getzlab/rnaseqc#39]
Hi. I downloaded rnaseqc but the command "rnaseqc" does not exist.

I downloaded with the following command:
`git clone --recursive https://github.com/broadinstitute/rnaseqc.git`

And got this in my folder:
args.hxx  bioio.hpp  cloudbuild.yaml  Dockerfile  LICENSE  Makefile  Metrics.md  python  README.md  SeqLib  src  test_data  THIRD-PARTY-LICENSES.md

But I didn't see rnaseqc command anywhere in folder or sub-folders.
When I try calling rnaseqc command:
```
$ ./rnaseqc
-bash: ./rnaseqc: No such file or directory
```

I also tried downloading Git LFS since it's required but when I unzipped and submitted the command `git lfs install` it said the command didn't exist. I tried `git-lfs` which is what I see in the folder, it says "cannot execute binary file".

I have CLIP data and ultimately want to plot read coverage across transcripts to see if there is preference for peaks to be at 5'UTR, CDS, or 3'UTR. I think rnaseqc tool will help me get there, like the figure at the bottom of page 11 of manual:
https://software.broadinstitute.org/cancer/cga/sites/default/files/data/tools/rnaseqc/RNA-SeQC_Help_v1.1.2.pdf

If rnaseqc won't help me get there, please let me know since this is the reason I want to use it.

Thank you.

**Comment by agraubert** [comment]
Hello,
To produce the binary for rnaseqc in the repo, you'll need to use the Makefile. The command
```
make
```
will read the Makefile and attempt to compile rnaseqc for your system. Alternatively, you can download pre-compiled static binaries from the [releases page](https://github.com/broadinstitute/rnaseqc/releases).

**Comment by agraubert** [comment]
I'm closing this issue as we haven't heard from you in a while. If you still need help feel free to comment and re-open this issue
