### ISSUE TITLE
Is “-strictMode” flag still valid?

### ISSUE THREAD

**Issue by silvernano** [getzlab/rnaseqc#51]
Hi,
I'm using rnaseqc.v2.3.6.linux and follow the the gtex-pipeline (https://github.com/broadinstitute/gtex-pipeline/tree/master/rnaseq) to get my gene counts. In a recent paper "The GTEx Consortium atlas of genetic regulatory effects across human tissues", it mentioned to add a “-strictMode” flag in RNA-SeQC to filter gene counts, so I tried it with the original pipeline which did not use this option. My code is like: rnaseqc ${genes_gtf} ${bam_file} . -s ${sample_id} --stranded rf -vv -strictMode, however, when I checked the metrics.tsv file, nothing changed, and the count table is the same. Is it expected? Should I use this option?

Thank you!

**Comment by agraubert** [comment]
Strict mode is no longer a supported flag, but it's behavior is still included. RNA-SeQC 2 considers these reads as "high quality" and metrics like the exonic rate are reported for all reads and just for high quality reads. Other metrics such as the exon cv exclusively use high quality reads

**Comment by xiyasong** [comment]
Hi! If I understand correctly, RNA-SeQC 2 already automatically include the filters used in the -strictMode to generate the count results(gene_reads.gct,gene_tpm.gct),  or should I manually choose the "high quality" ones in some way? Appreciate it if you can reply!

**Comment by francois-a** [comment]
Hi, yes, these are automatically applied in v2.
