### ISSUE TITLE
Question about reading BAM file in S3 bucket

### ISSUE THREAD

**Issue by gujjas** [getzlab/rnaseqc#55]
Hi,

I would like to know if RNA-SeQC supports reading BAM files from AWS S3 bucket?

Thanks

**Comment by agraubert** [comment]
RNA-SeQC will not automatically parse s3 or gs urls and read from buckets, however it does support streaming so a command like
```
rnaseqc annotation.gtf <(aws s3 cp s3://alignment.bam) ...
```
should work

**Comment by gujjas** [comment]
Thank you so much, Aaron. I'll try your command to see if it works.

On a slightly different note, I am having issues installing the tool - using git clone or downloading the source file, I get the error below:

```
collect2: error: ld returned 1 exit status
make: *** [rnaseqc] Error 1
```

```
[rnaseqc-2.4.0]$ gcc --version
gcc (GCC) 5.5.0
```

Can you please help.
Thanks

**Comment by agraubert** [comment]
Is there any more to that error message?

**Comment by gujjas** [comment]
[make.error.txt](https://github.com/getzlab/rnaseqc/files/5761005/make.error.txt)

Hi Aaron,

I've attached the error file for your reference. Please let me know if you need anything else.

Thanks
Shar

**Comment by agraubert** [comment]
If you're compiling from source, try opening the makefile and setting [ABI](https://github.com/getzlab/rnaseqc/blob/master/Makefile#L6) to 0. `make clean && make` should work then.

Alternatively, you can download our [precompiled binaries](https://github.com/getzlab/rnaseqc/releases) for most versions of RNA-SeQC or use our docker image: `gcr.io/broad-cga-aarong-gtex/rnaseqc`

**Comment by gujjas** [comment]
Hi Aaron,

Thank you so much for the reply. Editing the makefile did not work, however the precompiled binary for linux seems to be working. Using the command you had shared earlier on collapsed gene level gtf file -  giving me this error:

```
./rnaseqc.v2.4.0.linux ../gencode.v25.genes.gtf <(aws s3 cp s3://s3bucketname/PROJ-123/test.bam) test

Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws: error: the following arguments are required: paths
BAM file shares no contigs with GTF
```

Thanks for helping.
Shar

**Comment by agraubert** [comment]
Sorry, I'm not super familiar with the aws CLI. Here's an edited version that should work:
```
rnaseqc annotation.gtf <(aws s3 cp s3://alignment.bam - ) ...
```

**Comment by gujjas** [comment]
Thank you so much. It works!

**Comment by agraubert** [comment]
Glad to hear! Let me know if you have any additional issues
