### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by cmatKhan** [getzlab/rnaseqc#58]
This may be my own error in setting up the Makefile -- apologies if so.

I have gotten this error when running `make` in the source dir:

```
$ make
g++ -O3  -o rnaseqc src/BED.o src/Expression.o src/GTF.o src/RNASeQC.o src/Metrics.o src/Fasta.o src/BamReader.o SeqLib/lib/libseqlib.a SeqLib/lib/libhts.a  -lboost_filesystem -lboost_regex -lboost_system -lz -llzma -lbz2 -lpthread
/bin/ld: SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o): unable to initialize decompress status for section .debug_info
/bin/ld: SeqLib/lib/libseqlib.a(libseqlib_a-BamReader.o): unable to initialize decompress status for section .debug_info
SeqLib/lib/libseqlib.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [rnaseqc] Error 1
```

Any suggestions?

**Comment by agraubert** [comment]
Can you tell me more about the system you're on? 

You can also use Pre-compiled binaries for Mac and Linux available on our [releases page](https://github.com/getzlab/rnaseqc/releases), or our docker image `gcr.io/broad-cga-aaron-gtex/rnaseqc`.

**Comment by cmatKhan** [comment]
```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

However, using the pre-compiled release worked -- should have done that to begin with. Thank you.

I noticed there was a closed issue from someone who was also using an older version of the compiler -- I suspect that was my issue.

**Comment by agraubert** [comment]
Well I'm glad we got you going. Let me know if you have any other issues
