### ISSUE TITLE
Strand argument clarification

### ISSUE THREAD

**Issue by cmatKhan** [getzlab/rnaseqc#59]
I should likely be able to interpret this without help, but this isn't clear to me:

  --stranded=[stranded]             Use strand-specific metrics. Only
                                    features on the same strand of a read
                                    will be considered. Allowed values are
                                    'RF', 'rf', 'FR', and 'fr'
                                    
Do ('RF', 'rf') and ('FR', 'fr') mean the same thing? Does RF mean 'reverse strand' and 'FR' mean 'forward strand'?

**Comment by agraubert** [comment]
This has to do with the order in which read pairs are sequenced:
* FR, fr: The first mate is the forward strand, second mate reverse
* RF, rf: The first mate is the reverse strand, second mate forward

When this argument is provided, RNA-SeQC uses this information to determine the strand of each read and will only intersect with features on that strand.

Please let me know if this answers your question

**Comment by cmatKhan** [comment]
Got it -- thank you!
