### ISSUE TITLE
How can I generate the figure reflecting the coverage over the gene body?

### ISSUE THREAD

**Issue by biozzq** [getzlab/rnaseqc#70]
Dear all,

I wonder that if I could generate the following figure (generated by RSeQC) using the results generated by rnaseqc?

![image](https://user-images.githubusercontent.com/15704257/174071994-50867324-843f-401e-8067-ff301922bf56.png)

Also, you have said that if the mean 3’ bias is 0.5, it means even coverage. In my experiment, this value is 0.286. Thus, is this good or bad for the rRNA-depleted library? In my mind, the above figure is the most straightforward way to visualize this bias.
```
Genes used in 3' bias   11907
Mean 3' bias    0.286089
Median 3' bias  0.180421
3' bias Std     0.282717
3' bias MAD_Std 0.227422
3' Bias, 25th Percentile        0.0513699
3' Bias, 75th Percentile        0.461538
Median of Avg Transcript Coverage       2.3769
Median of Transcript Coverage Std       2.88895
Median of Transcript Coverage CV        1.4343
Median Exon CV  0.323636
Exon CV MAD     0.308915
```

Best wishes,
Zheng zhuqing

**Comment by agraubert** [comment]
Hey Zheng,

RNA-SeQC does not report the raw coverage data like the one you posted above. If you want to collect that data, you could use something like bedtools to intersect your annotation and a filtered bam file, then plot it as desired.
With regards to your 3' bias, we don't really like to make that call for our users, but it's definitely a reasonable score for rRNA depleted libraries. I'd recommend you look at your other samples and see if 0.286 is an outlier for your data or not.
