### ISSUE TITLE
rnaseqc v2.4.2 unable to parse collapsed genes GTF

### ISSUE THREAD

**Issue by limrock1** [getzlab/rnaseqc#73]
Hi,

After collapsing the v39 annotation GTF file downloaded from gencode, I'm getting the error below when calling rnaseqc:

$ python3 collapse_annotation.py gencode.v39.annotation.gtf gencode.v39.genes_collapsed.gtf

Parsing GTF: 61533 genes processed
Collapsing transcripts

$ rnaseqc N0037.Aligned.sortedByCoord.out.md.bam gencode.v39.genes_collapsed.gtf test -s N0037 -vv

Reading GTF Features...

Failed to parse the GTF: Unable to parse feature type. Invalid GTF line: ?BC?)?]??5?M?U?u?UqB?Qr5??H AF??H?,?B?ݻ??V٭ￛ??????ZvU?w????????????????۾?ſ?????????~#??oe???Fޯ_ZOskcy???J????ᕖJZ?b~????H/????????/??????e??????????G?Qs?:?T??9?m????}??FK,'??????2?D?{5?w]6T?t?^<?䂰?!/'??][^c?Ñ'?+0??????ֻ???-.-W??I?Q?\?\6?????u23???88??8??.#'?!??P??'?b???vY`;?4??????~Fa??V????%1rd???*?N?R+??s?)??!fo zzͲE]???g??)"Z?й?????

Checking forums, I tried alternate GTF files with 'gene_type' set to 'gene_biotype' with no luck. Am I missing something?

Thanks,
Sean.

**Comment by agraubert** [comment]
Swap the order of your command-line arguments, the gtf should come before the bam. It should be
`$ rnaseqc gencode.v39.genes_collapsed.gtf N0037.Aligned.sortedByCoord.out.md.bam test -s N0037 -vv`

**Comment by limrock1** [comment]
Crikey! Okay you're right, it works now, thanks. Maybe a good idea to set flags for input paramaters including gtf and bam.
