### ISSUE TITLE
So difficult to prepare a gtf for rnaseqc

### ISSUE THREAD

**Issue by xiekunwhy** [getzlab/rnaseqc#81]
Hi,

It is so hard to prepare a gtf to run rnaseqc, why don't provide a generic script to covert a generic gtf to rnaseqc accepted gtf?

So difficult !
So difficult !

Best,
Kun

**Comment by xiekunwhy** [comment]
Hi,

The script you have mentioned is not so general as it require some information we usually do not have, like transcript_type and exon id. In many cases, a gtf only have transcript_id and gene_id.

Best,
Kun

**Comment by francois-a** [comment]
These fields are mandatory in the GENCODE GTF specification, which the parser is based on:
https://www.gencodegenes.org/pages/data_format.html

**Comment by xiekunwhy** [comment]
So it just design for dealing with GENCODE GTF. In other cases like transcript calling results using stringtie2 or scallop2, there is no transcript_type as we don't know which type a transcript is.
Rnaseqc is a good tool. Thank you!
Best,
Kun

**Comment by KristinaGagalova** [comment]
is there possible to add a script in this github repo that does the job? Thank you for sharing the commands

**Comment by Rohit-Satyam** [comment]
I agree with @xiekunwhy. The [collapse_annotation.py](https://github.com/broadinstitute/gtex-pipeline/blob/master/gene_model/collapse_annotation.py) is such a mess for non-model organisms. I haven't tested this but I am trying AGAT `agat_sp_fix_overlaping_genes.pl` for this purpose.
