### ISSUE TITLE
Exon_reads.gct.gz file raw count data are not integer

### ISSUE THREAD

**Issue by zhangpicb** [getzlab/rnaseqc#88]
Dear @agraubert @joshua-gould @francois-a @dmcgoldrick 

Thanks for the great tool!

I have a simple question.Why exon_reads.gct.gz file raw count data are not integer?gene_reads.gct.gz files raw count data are integer?

Thanks in advanced!

**Comment by agraubert** [comment]
The exon reads file counts partial reads (length of intersection with an exon / length of the read)

**Comment by zhangpicb** [comment]
The exon reads file counts value is  sum(length of intersection with the exon )/sum(full length of the read overlap the exon) ?

**Comment by agraubert** [comment]
`sum([length of intersection / read length], [length of intersection / read length] ....)`

https://github.com/getzlab/rnaseqc/blob/6465cb4f707998d5b34ea52ab5e605af47300086/src/Expression.cpp#L345-L346

**Comment by zhangpicb** [comment]
Thanks a ton!
