### ISSUE TITLE
Please consider replacing agutils.status_bar with tqdm

### ISSUE THREAD

**Issue by lrvdijk** [getzlab/rnaseqc#89]
I am trying to create updated bioconda packages for rnaseqc (see [(1)](https://github.com/bioconda/bioconda-recipes/pull/51342) and [(2)](https://github.com/bioconda/bioconda-recipes/pull/51344)).

I was also trying to create a separate bioconda recipe for the python utils, as published on PyPI (see (2) above). That package, however, depends on `agutil`, a package not available on either bioconda or conda-forge. 

Since rnaseqc only uses agutil for a progress bar, would it be an idea to instead use the much more widely used library [`tqdm`](https://github.com/tqdm/tqdm) for that?

I could open a PR if desired.

Thanks!

**Comment by francois-a** [comment]
done.
